gig_app_api/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :gigs
  resources :users, only: [:index, :show, :update] do
    resources :gigs, only: [:create, :update, :index, :show]
  end
  resources :sessions, only: [:create]
  resources :registrations, only: [:create] 
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"
  # root to: "static#home" 
end

gig_app_api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

gig_app_api/app/models/gig.rb
class Gig < ApplicationRecord
    belongs_to :user
end

gig_app_api/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :email
    validates_uniqueness_of :email 
    has_many :gigs
end

gig_app_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

gig_app_api/app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
    extend ActiveSupport::Concern 

    included do
        before_action :set_current_user
    end

    def set_current_user
        if session[:user_id]
            @current_user = User.find(session[:user_id])
        end
    end
end

gig_app_api/app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [ :show, :edit, :update, :destroy]

  # GET /gigs
  # GET /gigs.json
  def index
    @gigs = Gig.all
    render json: @gigs 
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    render json: @gig
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)
    @gig.user_id = params[:user_id]
      if @gig.save
        render :show, status: :created, location: @gig
      else
        render json: @gig.errors, status: :unprocessable_entity 
      end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
      if @gig.update(gig_params)
        render json: @gig
      else
       render json: @gig.errors, status: :unprocessable_entity
      end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gig_params
      params.require(:gig).permit(:title, :client, :client_contact, :location, :date, :price, :user_id, :id, :created_at, :updated_at, :time, :user_id)
    end

end

gig_app_api/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def create 
        user = User.create!(
            email: params["user"]["email"], 
            password: params["user"]["password"],
            password_confirmation: params["user"]["password_confirmation"]
        )
        if user 
            session[:user_id] = user.id
            render json: {
                status: :created, 
                user: user
            }
        else
            render json: {status: 500}
        end
    end
end

gig_app_api/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include CurrentUserConcern
    def create 
        user = User
                .find_by(email: params["user"]["email"])
                .try(:authenticate, params["user"]["password"])

        if user
            session[:user_id] = user.id 
            render json: {
                status: :created, 
                logged_in: true, 
                user: user 
            }
        else
            render json: {status: 401}
        end
    end 
    
    def logged_in
        if @current_user
            render json: {
                logged_in: true, 
                user: @current_user.as_json(include: :gigs)
            }
        else
            render json: {
                logged_in: false
            }
        end
    end
    def logout
        reset_session
        render json: {status: 200, logged_out: true }
    end
end 

gig_app_api/app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home 
        render json: {status: "It's working"}
    end
end

gig_app_api/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :update, :destroy]

    def index
        @users = User.all 
        render json: @users
    end


    
    def show
        render json: @user.to_json(include: :gigs)
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:email).permit(:gigs, :id)
    end
end

gig_app_api/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        render json: { status: 200, message: "Gig App Api" }
      end
end

gig_app_api/app/helpers/application_helper.rb
module ApplicationHelper
end

gig_app_api/app/helpers/gigs_helper.rb
module GigsHelper
end

gig_app_api/app/helpers/users_helper.rb
module UsersHelper
end

gig_app_api/app/helpers/welcome_helper.rb
module WelcomeHelper
end

gig_app_api/app/views/gigs/_form.html.erb
<%= form_with(model: gig, local: true) do |form| %>
  <% if gig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gig.errors.count, "error") %> prohibited this gig from being saved:</h2>

      <ul>
        <% gig.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :client %>
    <%= form.text_field :client %>
  </div>

  <div class="field">
    <%= form.label :client_contact %>
    <%= form.text_field :client_contact %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gig_app_api/app/views/gigs/edit.html.erb
<h1>Editing Gig</h1>

<%= render 'form', gig: @gig %>

<%= link_to 'Show', @gig %> |
<%= link_to 'Back', gigs_path %>

gig_app_api/app/views/gigs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gigs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Client</th>
      <th>Client contact</th>
      <th>Location</th>
      <th>Date</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gigs.each do |gig| %>
      <tr>
        <td><%= gig.title %></td>
        <td><%= gig.client %></td>
        <td><%= gig.client_contact %></td>
        <td><%= gig.location %></td>
        <td><%= gig.date %></td>
        <td><%= gig.price %></td>
        <td><%= link_to 'Show', gig %></td>
        <td><%= link_to 'Edit', edit_gig_path(gig) %></td>
        <td><%= link_to 'Destroy', gig, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gig', new_gig_path %>

gig_app_api/app/views/gigs/new.html.erb
<h1>New Gig</h1>

<%= render 'form', gig: @gig %>

<%= link_to 'Back', gigs_path %>

gig_app_api/app/views/gigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gig.title %>
</p>

<p>
  <strong>Client:</strong>
  <%= @gig.client %>
</p>

<p>
  <strong>Client contact:</strong>
  <%= @gig.client_contact %>
</p>

<p>
  <strong>Location:</strong>
  <%= @gig.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @gig.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @gig.price %>
</p>

<%= link_to 'Edit', edit_gig_path(@gig) %> |
<%= link_to 'Back', gigs_path %>

gig_app_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GigAppApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>